### ISSUE TITLE
variable connected_device not defined

### ISSUE THREAD

**Issue by cosmo-developer** [cosmo-organization/android-sploit#1]
https://github.com/cosmo-organization/android-sploit/blob/14fa9913675490e7b85536a539380b43405b2d55/com/cosmo/sploit/tools.py#L64

**Comment by sonukumar659** [comment]
> https://github.com/cosmo-organization/android-sploit/blob/14fa9913675490e7b85536a539380b43405b2d55/com/cosmo/sploit/tools.py#L64

self.abd_c(f'-s {_connected_device_name} uinstall {_installed_apk_package}')

**Comment by cosmo-developer** [comment]
It's fixed now
